=== orcmid/orcmid.github.io/A2HostingWeb/dmware/standards/IETF/rfc2629.dtd
<!--
  DTD for the RFC document series, draft of 99-01-30
  -->


<!--
  Contents

    DTD data types

    The top-level

    Front matter

    The Body

    Back matter
  -->


<!--
  DTD data types:

        entity        description
        ======        ===============================================
        NUMBER        [0-9]+
        NUMBERS       a comma-separated list of NUMBER

        DAY           the day of the month, e.g., "1"
        MONTH         the month of the year, e.g., "January"
        YEAR          a four-digit year, e.g., "1999"

        URI           e.g., "http://invisible.net/"

        ATEXT/CTEXT   printable ASCII text (no line-terminators)

        TEXT          character data
  -->


<!ENTITY % NUMBER     "CDATA">
<!ENTITY % NUMBERS    "CDATA">

<!ENTITY % DAY        "CDATA">
<!ENTITY % MONTH      "CDATA">
<!ENTITY % YEAR       "CDATA">

<!ENTITY % URI        "CDATA">

<!ENTITY % ATEXT      "CDATA">
<!ENTITY % CTEXT      "#PCDATA">

<!ENTITY % TEXT       "#PCDATA">

<!ENTITY   rfc.number "XXXX">


<!--
  The top-level
  -->


<!--
  attributes for the "rfc" element are supplied by the RFC
  editor. when preparing drafts, authors should leave them blank.

  the "seriesNo" attribute is used if the category is, e.g., BCP.
  -->
<!ELEMENT rfc         (front,middle,back?)>
<!ATTLIST rfc
          number      %NUMBER;           #IMPLIED
          obsoletes   %NUMBERS;          ""
          updates     %NUMBERS;          ""
          category    (std|bcp|info|exp|historic)
                                         "info"
          seriesNo    %NUMBER;           #IMPLIED
          ipr         (full2026|noDerivativeWorks2026|none)
                                         #IMPLIED
          docName     %ATEXT;            #IMPLIED> 

<!--
  Front matter
  -->


<!ELEMENT front       (title,author+,date,area*,workgroup*,keyword*,
                       abstract?,note*)>

<!-- the "abbrev" attribute is used for headers, etc. -->
<!ELEMENT title       (%CTEXT;)>
<!ATTLIST title
          abbrev      %ATEXT;            #IMPLIED> 

<!ELEMENT author      (organization,address?)>
<!ATTLIST author
          initials    %ATEXT;            #IMPLIED
          surname     %ATEXT;            #IMPLIED
          fullname    %ATEXT;            #IMPLIED>

<!ELEMENT organization
                      (%CTEXT;)>
<!ATTLIST organization
          abbrev      %ATEXT;            #IMPLIED> 
 
<!ELEMENT address     (postal?,phone?,facsimile?,email?,uri?)>

<!-- at most one of each the city, region, code, and country
     elements may be present -->
<!ELEMENT postal      (street+,(city|region|code|country)*)>
<!ELEMENT street      (%CTEXT;)>
<!ELEMENT city        (%CTEXT;)>
<!ELEMENT region      (%CTEXT;)>
<!ELEMENT code        (%CTEXT;)>
<!ELEMENT country     (%CTEXT;)>
<!ELEMENT phone       (%CTEXT;)>
<!ELEMENT facsimile   (%CTEXT;)>
<!ELEMENT email       (%CTEXT;)>
<!ELEMENT uri         (%CTEXT;)>

<!ELEMENT date        EMPTY>
<!ATTLIST date
          day         %DAY;              #IMPLIED
          month       %MONTH;            #REQUIRED
          year        %YEAR;             #REQUIRED>

<!-- meta-data... -->
<!ELEMENT area        (%CTEXT;)>
<!ELEMENT workgroup   (%CTEXT;)>
<!ELEMENT keyword     (%CTEXT;)>

<!ELEMENT abstract    (t)+>
<!ELEMENT note        (t)+>
<!ATTLIST note
          title       %ATEXT;            #REQUIRED>


<!--
  The body
  -->


<!ELEMENT middle      (section)+>

<!ELEMENT section     (t|figure|section)*>
<!ATTLIST section
          anchor      ID                 #IMPLIED
          title       %ATEXT;            #REQUIRED>

<!ELEMENT t           (%TEXT;|list|figure|xref|eref|iref|vspace)*>
<!ATTLIST t
          hangText    %ATEXT;            #IMPLIED>

<!-- the value of the style attribute is inherited from the closest 
     parent -->
<!ELEMENT list        (t+)>
<!ATTLIST list
          style       (numbers|symbols|hanging|empty)
                                         "empty">

<!ELEMENT xref        (%CTEXT;)>
<!ATTLIST xref
          target      IDREF              #REQUIRED
          pageno      (true|false)       "false">

<!ELEMENT eref        (%CTEXT;)>
<!ATTLIST eref
          target      %URI;              #REQUIRED>

<!ELEMENT iref        EMPTY>
<!ATTLIST iref
          item        %ATEXT;            #REQUIRED
          subitem     %ATEXT;            "">

<!ELEMENT vspace      EMPTY>
<!ATTLIST vspace
          blankLines  %NUMBER;           "0">

<!ELEMENT figure      (preamble?,artwork,postamble?)>
<!ATTLIST figure
          anchor      ID                 #IMPLIED
          title       %ATEXT;            "">

<!ELEMENT preamble    (%TEXT;|xref|eref|iref)*>
<!ELEMENT artwork     (%TEXT;)*>
<!ATTLIST artwork
          xml:space   (default|preserve) "preserve"
          name        %ATEXT;            ""
          type        %ATEXT;            "">

<!ELEMENT postamble   (%TEXT;|xref|eref|iref)*>


<!--
  Back matter
  -->


<!-- sections, if present, are appendices -->
<!ELEMENT back        (references?,section*)>

<!ELEMENT references  (reference+)>
<!ELEMENT reference   (front,seriesInfo*)>
<!ATTLIST reference
          anchor      ID                 #IMPLIED
          target      %URI;              #IMPLIED>
<!ELEMENT seriesInfo  EMPTY>
<!ATTLIST seriesInfo
          name        %ATEXT;            #REQUIRED
          value       %ATEXT;            #REQUIRED>

=== orcmid/orcmid.github.io/A2HostingWeb/dmware/standards/IETF/rfc2629-writing-rfcs.xml
<?xml version="1.0"?>
<!DOCTYPE rfc SYSTEM "rfc2629.dtd">
<?rfc toc="yes"?>
<rfc number="2629">
<front>
<title>Writing I-Ds and RFCs using XML</title>
<author initials="M.T." surname="Rose" fullname="Marshall T. Rose">
<organization>Invisible Worlds, Inc.</organization>
<address>
<postal>
<street>660 York Street</street>
<city>San Francisco</city> <region>CA</region> <code>94110</code>
<country>US</country>
</postal>
<phone>+1 415 695 3975</phone>
<email>mrose@not.invisible.net</email>
<uri>http://invisible.net/</uri>
</address>
</author>
<date month="June" year="1999" />
<area>General</area>
<keyword>RFC</keyword>
<keyword>Request for Comments</keyword>
<keyword>I-D</keyword>
<keyword>Internet-Draft</keyword>
<keyword>XML</keyword>
<keyword>Extensible Markup Language</keyword>
<abstract><t>This memo presents a technique for using XML
(Extensible Markup Language)
as a source format for documents in the Internet-Drafts (I-Ds) and
Request for Comments (RFC) series.</t></abstract>
</front>
<middle>
<section title="Introduction">
<t>This memo describes how to write a document for the I-D and RFC series
using <xref target="XML">the Extensible Markup Language</xref> (XML).
This memo has three goals:
<list style="numbers">
<t>To describe a simple XML Document Type Definition (DTD) that is
powerful enough to handle the simple formatting requirements of RFC-like
documents whilst allowing for meaningful markup of descriptive
qualities.</t>
<t>To describe software that processes XML source files,
including a tool that produces documents
conforming to <xref target="refs.RFC2223">RFC 2223</xref>,
HTML format, and so on.</t>
<t>To provide the proof-of-concept for the first two goals
(this memo was written using this DTD and produced using that
software).</t>
</list>
</t>
<t>It is beyond the scope of this memo to discuss the political
ramifications of using XML as a source format for RFC-like documents.
Rather,
it is simply noted that adding minimal markup to plain text:
<list style="symbols">
<t>allows the traditional production of textual RFC-like documents using
familiar editors;</t>
<t>requires some, albeit minimal, additions to existing software
environments; and,</t>
<t>permits information to be organized, searched, and retrieved
using both unstructured and structured mechanisms.</t>
</list>
</t>
</section>
<section title="Using the DTD to Write I-Ds and RFCs">
<t>We do not provide a formal or comprehensive description of XML.
Rather,
this section discusses just enough XML to use a Document Type
Declaration (DTD) to write RFC-like documents.</t>
<t>If you're already familiar with XML,
skip to <xref target="rfc.dtd" /> to look at the DTD.</t>
<section anchor="xml_basics" title="XML basics">
<t>There are very few rules when writing in XML,
as the syntax is simple.
There are five terms you'll need to know:
<list style="numbers">
<t>An "element" usually refers to a start tag, an end tag, and all the
characters in between,
e.g.,
"&lt;example&gt;text and/or nested elements&lt;/example&gt;"</t>
<t>An "empty element" combines the start tag and the end tag,
e.g.,
"&lt;empty/&gt;".
You don't find these in HTML.</t>
<t>An "attribute" is part of an element.
If present, they occur in the start tag, e.g.,
"&lt;example name='value'&gt;".
Of course,
they can also appear in empty elements, e.g.,
"&lt;empty name='value'/&gt;".</t>
<t>An "entity" is a textual macro that starts with "&amp;".
Don't worry about these,
you'll only use them whenever you want to put a "&amp;" or a "&lt;" in
your text.</t>
<t>A "token" is a string of characters.
The first character is either a letter or an underscore ("_").
Any characters that follow are either letters, numbers, an
underscore, or a period (".").</t>
</list>
</t>
<figure>
<preamble>First,
start your source file with an XML declaration,
a reference to the DTD,
and the "rfc" element:</preamble>
<artwork><![CDATA[
    <?xml version="1.0"?>
    <!DOCTYPE rfc SYSTEM "rfc]]>&rfc.number;<![CDATA[.dtd">
    <rfc>
        ...
    </rfc>
]]></artwork>
<postamble>Ignore the first two lines
-- the declaration and the reference --
and simply treat them as opaque strings.
Nothing else should be present after the "&lt;/rfc&gt;" tag.</postamble>
</figure>
<t>Second,
make sure that all elements are properly matched and nested.
A properly matched element that starts with
"&lt;example&gt;" is eventually followed with "&lt;/example&gt;".
(Empty elements are always matched.)
Elements are properly nested when they don't overlap.</t>
<figure>
<preamble>For example,</preamble>
<artwork><![CDATA[
    <outer>
        ...
        <inner>
            ...
        </inner>
        ...
    </outer>
]]></artwork>
<postamble>is properly nested.</postamble>
</figure>
<figure>
<preamble>However,</preamble>
<artwork><![CDATA[
    <outer>
        ...
        <inner>
            ...
        </outer>
        ...
    </inner>
]]></artwork>
<postamble>overlaps, so the elements aren't properly nested.</postamble>
</figure>
<t>Third,
never use "&lt;" or "&amp;" in your text.
Instead, use either "&amp;lt;" or "&amp;amp;", respectively.</t>
<t>Fourth,
there are two quoting characters in XML, 'apostrophe' and "quotation".
Make sure that all attributes values are quoted,
e.g., "&lt;example name='value'&gt;",
If the value contains one of the quoting characters,
then use the other to quote the value,
e.g., "&lt;example name='"'&gt;",
If the value contains both quoting characters,
then use one of them to quote the value,
and replace occurrances of that character in the attribute value with
either '&amp;apos;' (apostrophe) or "&amp;quot;" (quotation),
e.g., "&lt;example name='"&amp;apos;"'&gt;".</t>
<figure>
<preamble>If you want to put a comment in your source file,
here's the syntax:</preamble>
<artwork><![CDATA[
        <!-- comments can be multiline,
         if you wish -->
]]></artwork>
</figure>
<t>Finally,
XML is case sensitive.</t>
</section>
<section anchor="front_matter" title="Front matter">
<figure>
<preamble>Immediately following the "&lt;rfc&gt;" tag is the "front"
element:</preamble>
<artwork><![CDATA[
    <?xml version="1.0"?>
    <!DOCTYPE rfc SYSTEM "rfc]]>&rfc.number;<![CDATA[.dtd">
    <rfc>
        <front>
            <title ...>
            <author ...>
            <author ...>
            <date ...>
            <area ...>
            <workgroup ...>
            <keyword ...>
            <keyword ...>
            <abstract ...>
            <note ...>
        </front>
        ...
    </rfc>
]]></artwork>
<postamble>(Note that in all examples,
indentation is used only for expository purposes.)</postamble>
</figure>
<t>The "front" element consists of a "title" element,
one or more "author" elements,
a "date" element,
one or more optional "area" elements,
one or more optional "workgroup" elements,
one or more optional "keyword" elements,
an optional "abstract" element.
and,
one or more optional "note" elements.</t>
<section title="The title Element">
<figure>
<preamble>The "title" element identifies the title of the document.
Because the title will be used in the headers of the document when formatted
according to <xref target="refs.RFC2223" />,
if the title is more than 42 characters,
then an abbreviation should also be provided,
e.g.,</preamble>
<artwork><![CDATA[
    <title abbrev="Much Ado about Nothing">
    The IETF's Discussion on "Source Format of RFC Documents"
    </title>
]]></artwork>
</figure>
</section>
<section anchor="author" title="The author Element">
<figure>
<preamble>Each "author" element identifies a document author.
Since a document may have more than one author,
more than one "author" element may be present.
If the author is a person,
then three attributes must be present in the "&lt;author&gt;" tag,
"initials", "surname", and "fullname",
e.g.,</preamble>
<artwork><![CDATA[
    <author initials="M.T." surname="Rose"
            fullname="Marshall T. Rose">
]]></artwork>
</figure>
<t>The "author" element itself consists of an "organization" element,
and,
an optional "address" element.</t>
<figure>
<preamble>The "organization" element is similar to the "title"
element,
in that an abbreviation may be paired with a long organization name
using the "abbrev" attribute, e.g.,</preamble>
<artwork><![CDATA[
    <organization abbrev="ISI">
        USC/Information Sciences Institute
    </organization>
]]></artwork>
</figure>
<t>The "address" element consists of an optional "postal" element,
an optional "phone" element,
an optional "facsimile" element,
an optional "email" element,
and,
an optional "uri" element.</t>
<figure>
<preamble>The "postal" element contains one or more "street" elements,
followed by any combination of "city", "region" (state or province),
"code" (zipcode or postal code), and "country" elements, e.g.,</preamble>
<artwork><![CDATA[
    <postal>
        <street>660 York Street</street>
        <street>M/S 40</street>
        <city>San Francisco</city> <region>CA</region>
        <code>94110</code>
        <country>US</country>
    </postal>
]]></artwork>
<postamble>This flexibility is provided to allow for different national
formats for postal addresses.
Note however,
that although the order of the "city", "region", "code", and "country"
elements isn't specified,
at most one of each may be present.
Regardless,
these elements must not be re-ordered during processing by an XML
application
(e.g., display applications must preserve the ordering of the
information contained in these elements).
Finally,
the value of the "country" element should be a two-letter
code from ISO 3166.</postamble>
</figure>
<figure>
<preamble>The "phone", "facsimile", "email", and "uri" elements are
simple, e.g.,</preamble>
<artwork><![CDATA[
    <phone>+1 415 695 3975</phone>
    <email>mrose@not.invisible.net</email>
    <uri>http://invisible.net/</uri>
]]></artwork>
</figure>
</section>
<section anchor="date" title="The date Element">
<figure>
<preamble>The "date" element identifies the publication date of the
